services:
  frontend:
    build: mern/frontend
    ports:
      - 5173:5173
    networks:
      - mern

  backend:
    build: mern/backend
    ports:
      - 5050:5050
    depends_on:
      - mongodb
    networks:
      - mern

  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
  mongoexpress:
    image: mongo-express:latest
    ports:
      - 8082:8081
    networks:
      - mern
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb


networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
