pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                git 'https://github.com/Umarhegde/Docker_project.git'
            }
        }
        stage('Build') {
            steps {
               sh '''
                    cd java-project
                    mvn clean install
                    ls -l target
                    '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t my-app:${BUILD_ID} .
                '''
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8081:8080 --name my-app-container my-app:${BUILD_ID}'
            }
        }
    }
}
